name: Pre-commit auto-update
on:
  schedule:
    - cron: '30 2 * * 0'
jobs:
  auto-update:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7"]
        poetry-version: ["1.2.2"]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install "poetry==${{ matrix.poetry-version }}"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install pre-commit
        run: pipx install pre-commit

      - name: Run pre-commit autoupdate
        run: pre-commit autoupdate

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: update/pre-commit-autoupdate
          title: Auto-update pre-commit hooks
          commit-message: "chore: Auto-update pre-commit hooks"
          body: |
            Update versions of tools in pre-commit
            configs to latest version
          labels: dependencies
